[package]
name = "aranya-idf-embedded"
version = "0.1.0"
authors = ["nikki-aranya <npoelma@spideroak.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.84"

[[bin]]
name = "aranya-idf-embedded"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "s"
lto = true
codegen-units = 1
#panic = "abort"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = []

[dependencies]
buggy = "0.1"
aranya-crypto = { version = "0.2", path = "../aranya-core/crates/aranya-crypto" }
#aranya-keygen = { version = "0.3", path = "../aranya-core/crates/aranya-keygen" }
aranya-policy-ifgen = { version = "0.3", path = "../aranya-core/crates/aranya-policy-ifgen" }
aranya-policy-vm = { version = "0.3", path = "../aranya-core/crates/aranya-policy-vm" }
aranya-runtime = { version = "0.3", path = "../aranya-core/crates/aranya-runtime" }

esp-idf-svc = { version = "0.51", features = ["critical-section", "embassy-time-driver", "embassy-sync", "experimental"] }

anyhow = "1"
log = "0.4"
thiserror = "2"

[build-dependencies]
embuild = "0.33"

[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "joltwallet/littlefs", version = "1.16" }