[package]
name = "aranya-embedded"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-backtrace = { version = "0.15", features = [
    "esp32s3",
    "exception-handler",
    "panic-handler",
    "println",
]}

esp-hal = { version = "0.23", features = [
    "esp32s3",
] }
esp-println = { version = "0.13", features = ["esp32s3", "log"] }
log = { version = "0.4" }
esp-alloc = { version = "0.6" }
embedded-io = "0.6"

embedded-io-async = "0.6"
embassy-net = { version = "0.6", features = [ "tcp", "udp", "dhcpv4", "medium-ethernet"] }

esp-wifi = { version = "0.12", default-features=false, features = [
    "esp32s3",
    "utils",
    "wifi",
    "esp-alloc",
    "log",
] }
heapless = { version = "0.8", default-features = false }
smoltcp = { version = "0.12", default-features = false, features = [
    "medium-ethernet",
    "proto-dhcpv4",
    "multicast",
    "proto-ipv4",
    "socket-dhcpv4",
    "socket-icmp",
    "socket-raw",
    "socket-tcp",
    "socket-udp",
] }
embassy-executor = { version = "0.7",  features = [
    "task-arena-size-12288",
] }
embassy-time     = { version = "0.4",  features = ["generic-queue-8"] }
esp-hal-embassy  = { version = "0.6",  features = ["esp32s3"] }
static_cell      = { version = "~2.1",  features = ["nightly"] }
critical-section = "~1.2"
enumset = "1.1.5"
edge-dhcp = "0.5.0"
edge-nal = "0.5.0"
edge-nal-embassy = "0.5.0"
# Used git as read is still with mutable ref in the crate
embedded-sdmmc = { git = "https://github.com/rust-embedded-community/embedded-sdmmc-rs" }
embedded-hal-bus = "0.3.0"
owo-colors = "4.1.0"
embedded-hal = "1.0.0"
ciborium = { version = "0.2.2", default-features = false }
getrandom = { version = "0.2.15", features = ["custom"] }
postcard = { version = "1.0.10", default-features = false, features = ["alloc"] }
serde = { version = "1.0.205", default-features = false, features = ["alloc"] }
aranya-runtime = "0.3.0"
aranya-policy-vm = "0.3.1"
aranya-crypto = "0.2.1"
aranya-envelope-ffi = "0.3.0"
aranya-crypto-ffi = "0.3.0"
aranya-device-ffi = "0.3.0"
aranya-idam-ffi = "0.3.0"
aranya-perspective-ffi = "0.3.0"
aranya-base58 = "0.1.0"
aranya-buggy = "0.1.0"

[build-dependencies]
ron = "0.8.1"
serde = {version = "1.0.215", features = ["derive"] }
aranya-policy-lang = "0.1.0"
aranya-policy-compiler = "0.3.0"
aranya-policy-vm = "0.3.1"
ciborium = { version = "0.2.2", default-features = false }
aranya-runtime = "0.3.0"
aranya-envelope-ffi = "0.3.0"
aranya-crypto-ffi = "0.3.0"
aranya-device-ffi = "0.3.0"
aranya-crypto = "0.2.1"
aranya-idam-ffi = "0.3.0"
aranya-perspective-ffi = "0.3.0"

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 3
overflow-checks = false
