[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = 1
RUSTDOCFLAGS = { value = "", condition = { env_not_set = ["RUSTDOCFLAGS"] } }

RUSTFLAGS = { value = "-Dwarnings", condition = { env_true = [
    "CARGO_MAKE_CI",
] } }

[config]
default_to_workspace = false
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true


[tasks.default]
description = "List tasks"
script = "cargo make --quiet --list-all-steps --hide-uninteresting"

# Correctness
[tasks.check-fmt]
dependencies = ["check-fmt-rust", "check-fmt-toml"]
description = "Check file formatting"

[tasks.fmt]
dependencies = ["fmt-rust", "fmt-toml"]
description = "Format files"

[tasks.check-fmt-rust]
category = "correctness"
description = "Check rust code formatting"
command = "scripts/cargo-fmt.sh"
args = ["--all", "--", "--check"]

[tasks.fmt-rust]
category = "correctness"
description = "Format rust code"
command = "scripts/cargo-fmt.sh"
args = ["--all"]

[tasks.check-fmt-toml]
category = "correctness"
description = "Check toml formatting"
script = "git ls-files -z '*.toml' | xargs -0 -- taplo fmt --check --diff"
dependencies = ["install-taplo"]

[tasks.fmt-toml]
category = "correctness"
description = "Format toml"
script = "git ls-files -z '*.toml' | xargs -0 taplo fmt"
dependencies = ["install-taplo"]

[tasks.install-taplo]
private = true
install_crate = { crate_name = "taplo-cli", version = "0.9.3", binary = "taplo", test_arg = [
    "-V",
] }
