[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --partition-table partitions.csv"

[env]
ESP_LOG="INFO"
ESP_WIFI_CONFIG_COUNTRY_CODE="US"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Tlinkall.x",
  "-Z", "stack-protector=all",
  "--cfg", "getrandom_backend=\"custom\"",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]

[profile.dev]
# Rust debug is too slow.
codegen-units = 1
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = false
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = "s"
overflow-checks = false
strip = true
panic = "abort"
