//! This code is @generated by `policy-ifgen`. DO NOT EDIT.
#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(clippy::duplicated_attributes)]
#![allow(clippy::enum_variant_names)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_imports)]
extern crate alloc;
use alloc::vec::Vec;
use aranya_policy_ifgen::{
    macros::{action, actions, effect, effects, value},
    text, BaseId, ClientError, Value, Text,
};
#[derive(Debug)]
pub enum Persistent {}
#[derive(Debug)]
pub enum Ephemeral {}
/// Enum of policy effects that can occur in response to a policy action.
#[effects]
pub enum Effect {
    LedColorChanged(LedColorChanged),
    TeamCreated(TeamCreated),
}
/// LedColorChanged policy effect.
#[effect]
pub struct LedColorChanged {
    pub r: i64,
    pub g: i64,
    pub b: i64,
}
/// TeamCreated policy effect.
#[effect]
pub struct TeamCreated {}
#[actions(interface = Persistent)]
pub enum PersistentAction {
    create_team(create_team),
    set_led(set_led),
}
#[actions(interface = Ephemeral)]
pub enum EphemeralAction {}
/// create_team policy action.
#[action(interface = Persistent)]
pub struct create_team {
    pub nonce: Vec<u8>,
}
/// set_led policy action.
#[action(interface = Persistent)]
pub struct set_led {
    pub r: i64,
    pub g: i64,
    pub b: i64,
}
