//! This code is @generated by `policy-ifgen`. DO NOT EDIT.
#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(clippy::duplicated_attributes)]
#![allow(clippy::enum_variant_names)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_imports)]
extern crate alloc;
use alloc::vec::Vec;
use aranya_policy_ifgen::{
    macros::{action, actions, effect, effects, value},
    text, BaseId, ClientError, Value, Text,
};
#[derive(Debug)]
pub enum Persistent {}
#[derive(Debug)]
pub enum Ephemeral {}
/// AmbientColor policy enum.
#[value]
pub enum AmbientColor {
    Black,
    Blue,
    Red,
    Green,
    Magenta,
    Cyan,
    Yellow,
    White,
}
/// Enum of policy effects that can occur in response to a policy action.
#[effects]
pub enum Effect {
    AmbientColorChanged(AmbientColorChanged),
    MessageReceived(MessageReceived),
    RainbowEffect(RainbowEffect),
    TeamCreated(TeamCreated),
}
/// AmbientColorChanged policy effect.
#[effect]
pub struct AmbientColorChanged {
    pub author: BaseId,
    pub color: AmbientColor,
}
/// MessageReceived policy effect.
#[effect]
pub struct MessageReceived {
    pub author: BaseId,
    pub msg: Text,
}
/// RainbowEffect policy effect.
#[effect]
pub struct RainbowEffect {
    pub author: BaseId,
}
/// TeamCreated policy effect.
#[effect]
pub struct TeamCreated {}
#[actions(interface = Persistent)]
pub enum PersistentAction {
    create_team(create_team),
    send_message(send_message),
    send_rainbow(send_rainbow),
}
#[actions(interface = Ephemeral)]
pub enum EphemeralAction {}
/// create_team policy action.
#[action(interface = Persistent)]
pub struct create_team {
    pub nonce: Vec<u8>,
}
/// send_message policy action.
#[action(interface = Persistent)]
pub struct send_message {
    pub author: BaseId,
    pub msg: Text,
}
/// send_rainbow policy action.
#[action(interface = Persistent)]
pub struct send_rainbow {
    pub author: BaseId,
}
